{{- if .Values.oauthProxy.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauthProxy.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mta.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth-proxy
type: Opaque
stringData:
  session-secret: {{ randAlphaNum 43 }}
{{- end }}
