{{- if .Values.oauthProxy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.oauthProxy.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mta.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth-proxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.{{ .Values.oauthProxy.routeName }}: >
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Values.oauthProxy.routeName }}"}}
{{- end }}
